a = input("Enter your name : ")
print("My name is",a)
x = input("Enter first number: ")
y = input("Enter second number: ")
print(x+y)
print(int(x)+ int(y))
f = int(input("Enter first number: "))
g = int(input("Enter second number: "))
print(f+g)
